### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by bblanchon** [bblanchon/WpfBindingErrors#1]

**Comment by BrunoJuchli** [comment]
are you open for pull requests?

**Comment by bblanchon** [comment]
Of course I am!
Go on, don't be shy :smile:

**Comment by BrunoJuchli** [comment]
How do you want to handle publishing of the nuget package? I you don't have a nuget account or don't want to manage i can publish the package.

How do you want to handle creating the package? Appveyor is a nice and free (for Open source..) CI platform. Of course one can also build it locally and publish it manually. I'd not go the full-blown-automatic route anyway, i don't expect there to be enough updates to be worth it.

How about an icon? [this](https://thenounproject.com/term/browser/49994/) i think might suit. However, attribution is required.

What about the license? It would be nice if you could specify a license on your repository. Then i can add it to the nuget package. --> Reason is that for some company users it should be clear that they are allowed to use it. If there's no license, that's actually not clear. At least that's how i interpret it :) I'd suggest Apache License 2.0 - but of course you're free to choose another.

**Comment by bblanchon** [comment]
I added the the LICENSE.md, with MIT license (that's the one I always use).

I would prefer handling the publishing by myself, if that's OK to you.
I'll create a NuGet account.

Thanks.

**Comment by BrunoJuchli** [comment]
Sure i do prefer you handling the publishing :)
I'll have to adapt the nuspec for the license.
Do you want to create an http://www.appveyor.com/ account for building on CI server? It can build the automatically build the csproj, the nuget package,... it can also publish the nuget package automatically to your own nuget feed (for testing purposes).

**Comment by bblanchon** [comment]
Thanks again!
