### ISSUE TITLE
NET Core 3.0 support

### ISSUE THREAD

**Issue by wonea** [bblanchon/WpfBindingErrors#7]
Please provide NET Core 3.0 support, and NuGet package.

**Comment by bblanchon** [comment]
Hi @wonea,

It's been a long time since I have done any C# development...
Would you be able to write a PR?

Best Regards,
Benoit

**Comment by wonea** [comment]
Yes, I can do. Do you want to target .NET Core 3.0 & .NET Framework?

**Comment by bblanchon** [comment]
I just published a [version 1.1.0](https://www.nuget.org/packages/WpfBindingErrors/1.1.0) that includes your patch.

**Comment by wonea** [comment]
Great, thanks!
